name: Publish a docker image
on:
    push:
    schedule:
        - cron:  '0 0 1 * *' # https://crontab.guru/every-month

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Login into docker
              run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io

            - name: Install requirements
              run: python -m pip install --upgrade pip && pip install -r ./requirements.txt

            - name: Build image
              run: "rkd :build"

            - name: Publish image
              run: "rkd :push"
